Repository apache/mynewt-nimble, pull requests merged in 2024-11, with the labels that each got.

#1813 BASS support for bttester.
  apps/bttester/pkg.yml
  apps/bttester/src/btp/btp_bap.h
  apps/bttester/src/btp/btp_gap.h
  apps/bttester/src/btp/bttester.h
  apps/bttester/src/btp_bap.c
  apps/bttester/src/btp_core.c
  apps/bttester/src/btp_gap.c
  apps/bttester/syscfg.yml
Labels: size/M, size/L

#1903 porting/linux: Fix warning about __USE_GNU redefinition
  porting/npl/linux/src/os_atomic.c
Labels: size/XS

#1747 Add support for PACS autopts tests
  apps/bttester/pkg.yml
  apps/bttester/src/btp/btp.h
  apps/bttester/src/btp/btp_pacs.h
  apps/bttester/src/btp/bttester.h
  apps/bttester/src/btp_core.c
  apps/bttester/src/btp_pacs.c
  apps/bttester/syscfg.yml
Labels: size/M

#1912 nimble/host: Add Number Complete Packets event validation
  nimble/host/src/ble_hs_hci_evt.c
Labels: host, size/XS

#1906 Fix condition in address recognition
  nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Labels: host, size/XS

#1916 Prepare for Apache NimBLE 1.8.0 release
  RELEASE_NOTES.md
  repository.yml
Labels: size/S

#1923 Apache NimBLE 1.8.0 release
  repository.yml
Labels: size/XS

#1922 nimble/ll: Set ext adv params v2 command bug fixes
  nimble/controller/src/ble_ll_adv.c
  nimble/controller/src/ble_ll_hci.c
Labels: controller, size/XS

#1924 nimble/ll: Fix extended features for fake dual mode
  nimble/controller/src/ble_ll_hci.c
Labels: controller, size/S

#1921 nimble/ll: Add connection update support for CSS
  nimble/controller/src/ble_ll_conn_hci.c
  nimble/controller/src/ble_ll_ctrl.c
Labels: controller, size/S

#1932 nimble/ll: make includes config dependent
  nimble/controller/src/ble_ll.c
Labels: controller, size/XS

#1914 nimble/ll: Check scheduler before sending connection request
  nimble/controller/src/ble_ll_conn.c
Labels: controller, size/S

#1809 apps/blestress: refactor logging
  apps/blestress/src/rx_stress.c
  apps/blestress/src/stress.c
  apps/blestress/src/stress_gatt.c
  apps/blestress/src/tx_stress.c
Labels: size/L

#1928 apps: Remove leaudio_broadcaster application
  apps/leaudio_broadcaster/pkg.yml
  apps/leaudio_broadcaster/src/audio_data.h
  apps/leaudio_broadcaster/src/main.c
  apps/leaudio_broadcaster/syscfg.yml
Labels: size/XS

#1935 apps: bttester: fix uart settings
  apps/bttester/src/uart_pipe.c
  apps/bttester/syscfg.yml
Labels: size/S
