Repository apache/mynewt-nimble, pull requests merged in 2025-05, with the labels that each got.

#2026 port: add ble_npl_hw_is_in_critical implementation
  porting/npl/freertos/include/nimble/nimble_npl_os.h
  porting/npl/freertos/src/npl_os_freertos.c
Labels: size/S

#2032 nimble/host: Add support for Anonymous address type
  nimble/host/src/ble_gap.c
  nimble/include/nimble/ble.h
Labels: host, size/XS, size/S

#2033 apps/bttester: Add error checks for setting adv data
  apps/bttester/src/btp_gap.c
Labels: size/XS

#2034 ci: Make CodeQL fail_on_error.py more robust
  .github/workflows/fail_on_error.py
Labels: size/XS, CI

#2035 apps/bttester: Filter policy setup & advertising data fix
  apps/bttester/src/btp_gap.c
Labels: size/S

#1964 apps: bttester: Implement notify / Remove set_mult
  apps/bttester/src/btp/btp_gatt.h
  apps/bttester/src/btp_gatt.c
Labels: size/S

#2037 nimble/bttester: Add option to enable/disable leaudio support
  apps/bttester/syscfg.yml
Labels: size/S

#2041 apps/bttester: Refactor reporting supported commands
  apps/bttester/src/btp/bttester.h
  apps/bttester/src/btp_bap.c
  apps/bttester/src/btp_core.c
  apps/bttester/src/btp_gap.c
  apps/bttester/src/btp_gatt.c
  apps/bttester/src/btp_gatt_cl.c
  apps/bttester/src/btp_l2cap.c
  apps/bttester/src/btp_mesh.c
  apps/bttester/src/btp_pacs.c
  apps/bttester/src/bttester.c
Labels: size/M
